export const PRODUCT_CREATED = "PRODUCT_CREATED";
export const UPLOAD_PHOTO_FAILED = "UPLOAD_PHOTO_FAILED";
export const UPLOAD_PHOTO_REQUEST = "UPLOAD_PHOTO_REQUEST";
export const UPLOAD_PHOTO_SUCCESS = "UPLOAD_PHOTO_SUCCESS";
